package com.pm.Project_Management_Server.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "users")
public class User {
//Specifies that the primary key value should be automatically generated by the database, typically using an auto-increment column.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String userName;
    private String password;
    private String email;

    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL)
    private ProjectLead projectLead;

    @Enumerated(EnumType.STRING)
    private UserType userType; // enum ADMIN, OTHER and MANAGER
}
