package com.pm.Project_Management_Server.entity;

import jakarta.persistence.*;

@Entity
public class User {
//Specifies that the primary key value should be automatically generated by the database, typically using an auto-increment column.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String userName;
    private String password;
    private String email;

    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL)
    private ProjectLead projectLead;


    private UserType userType; // enum ADMIN, OTHER and MANAGER
}
